#
# Vagrant configuration for a demo of Vagrant and Puppet with VirtualBox and AWS
#
# NOTES FOR AWS:
# Make sure you install the Vagrant AWS plugin...
#   vagrant plugin install vagrant-aws
#
# Set environment variables for your AWS creds...
#   export AWS_ACCESS_KEY="AKXXXXXXXXXXXXXXX"
#   export AWS_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#
# Make sure you add the following dummy box...
#   vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
#
# Use the following command to spin up the box in AWS...
#   vagrant up appserver3 --provider=aws
#
# requires VirtualBox 4.2+ and Vagrant 1.5.0+
Vagrant.require_version ">= 1.5.0"
VAGRANTFILE_API_VERSION = "2"

VAGRANT_BOX = "ubuntu/trusty32" # https://vagrantcloud.com/ubuntu/trusty32
#VAGRANT_BOX = "ubuntu/trusty64" # https://vagrantcloud.com/ubuntu/trusty64
CODE_FOLDER = "/opt/code/vagrant-puppet-demo"

nodes = [
  { :hostname => "appserver1", :ip => "192.168.0.41", :role => "appserver", :provider => "virtualbox" },
  { :hostname => "appserver2", :ip => "192.168.0.42", :role => "appserver", :provider => "virtualbox" },
  { :hostname => "appserver3", :ip => "192.168.0.43", :role => "appserver", :provider => "aws" },
  { :hostname => "appserver4", :ip => "192.168.0.44", :role => "appserver", :provider => "aws" },
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      if node[:provider] == "virtualbox"
        node_config.vm.box = VAGRANT_BOX
        node_config.vm.hostname = node[:hostname] + ".box"
        node_config.vm.network :private_network, ip: node[:ip]
        $ssh_username = "vagrant"
      elsif node[:provider] == "aws"
        node_config.vm.box = "dummy"
        $ssh_username = "ubuntu"
        #node_config.ssh.username = "vagrant"
      end

      node_config.vm.synced_folder CODE_FOLDER, "/home/vagrant/code"

      if node[:provider] == "virtualbox"
        node_config.vm.provider :virtualbox do |vb|
          vb.name = node[:hostname]
          vb.memory = node[:ram] ? node[:ram] : 512
          vb.cpus = node[:cpus] ? node[:cpus] : 1
        end
      end

      if node[:provider] == "aws"
        config.vm.provider :aws do |aws, override|
          aws.keypair_name = "vagrant-aws"
          override.ssh.private_key_path = "~/.ssh/vagrant-aws.pem"
          aws.instance_type = "m3.medium"
          aws.security_groups = "vagrant"
          aws.region = "us-west-2"
          aws.ami = "ami-6ac2a85a"
          override.ssh.username = $ssh_username
          aws.tags = {
            "Name" => node[:hostname],
          }
        end
      end

      # update package lists and install Puppet prior to running Puppet
      config.vm.provision :shell, :path => "bootstrap.sh"

      # provision the VM using Puppet
      node_config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.manifest_file = "site.pp"
        puppet.module_path = "puppet/modules"
        puppet.facter = {
          "fqdn"         => node[:hostname],
          "instancerole" => node[:role],
          "ip_appserver" => node[:ip],
          "ssh_username" => $ssh_username
        }
      end
    end
  end
end
